####################################################
############## Text/String Operations
####################################################

In [9]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import numpy as np  
import re  # regular expressions like '+', '*'
import nltk  # The Natural Language Toolkit
from sklearn.datasets import load_files  
# nltk.download('popular') 
# will download stopwords, punkt etc # download in default dir else error later on
import pickle  
from nltk.corpus import stopwords
from nltk import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [91]:
# read from local
with open('text1', 'r') as txt1:
    txt1 = txt1.readlines()
txt1

['This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also\n',
 'This is 2nd line\n',
 'This is 3rd line\n']

In [438]:
# create string for future ops
str1 = txt1[0]
print(str1)
strx = "xyz abc ttt ttt pqr cqr pqt hhx hxxz"

This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also



In [8]:
# write in local
with open('text2', 'w') as txt2:
    txt2.writelines(txt1)

In [25]:
# remove special chars from 'string'
print(txt1[0])
temp = [re.sub('[^A-Za-z0-9]+', '', x) for x in txt1[0].split()] # removes special chars
print(temp)
temp = ' '.join(temp) # joins words
print(temp)
temp = ' '.join(temp.split()) # removes extra spaces from middle
print(temp)

This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also

['This', 'is', 'practice', 'data', 'created', 'for', 'text', 'process11ing', 'so', '', '', 'added', 'some', 'special', 'charac22ters', 'also']
This is practice data created for text process11ing so   added some special charac22ters also
This is practice data created for text process11ing so added some special charac22ters also


In [45]:
# remove special chars from 'list of strings'; leave alphanumeric
print(txt1)
def rm_special_from_str(str1):
    temp = [re.sub('[^A-Za-z0-9]+', '', x) for x in str1.split()] # removes special chars
    temp = ' '.join(temp) # joins words
    temp = ' '.join(temp.split()) # removes extra spaces from middle
    return temp
temp = [rm_special_from_str(x) for x in txt1]
print(temp)

['This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also\n', 'This is 2nd line\n', 'This is 3rd line\n']
['This is practice data created for text process11ing so added some special charac22ters also', 'This is 2nd line', 'This is 3rd line']


In [53]:
# remove numeric from words in string
str1 = txt1[1]
print(str1) # This is 2nd line
temp = re.sub('[0-9]+', '', str1)
print(temp) # 'This is nd line'

This is 2nd line

This is nd line



In [80]:
# replace sub-string in multiple lines (only if sub-str is not complete word)
print(txt1)
def replace_substr(str1):
    temp = [x.replace('is','ss') if x!='is' else x for x in str1.split()]
    temp = ' '.join(temp)
    return(temp)
temp = [replace_substr(x) for x in txt1]
temp

['This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also\n', 'This is 2nd line\n', 'This is 3rd line\n']


['Thss is practice data create!!d for text process11ing so @# ``- added some special charac22ters also',
 'Thss is 2nd line',
 'Thss is 3rd line']

In [83]:
# remove leading and training spaces
str1 = '   abc xyz  pqr  '
print(str1.strip())
# remove all extra spaces
print(' '.join(str1.split()))

abc xyz  pqr
abc xyz pqr


In [94]:
# word count in string
len(str1.split())

16

In [101]:
# remove words from string containing a sub-string
print(str1)
str2 = [x for x in str1.split() if 'act' not in x]
print(' '.join(str2))

This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also

This is data create!!d for text process11ing so @# ``- added some special charac22ters also


In [107]:
# remove words from string starting with a character
print(str1)
str2 = [x for x in str1.split() if not x.startswith('@')] # similarly 'endswith'
' '.join(str2)

This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also



'This is practice data create!!d for text process11ing so ``- added some special charac22ters also'

In [115]:
# add a word as 1st word of string
print(str1)
str2 = '1st-word ' + str1
str2
# remove 1st word of string
str2 = str1.replace(  str1.split()[0], ''  ).strip()
str2
# remove last word of string
str2 = str1.replace(  str1.split()[ len(str1.split())-1 ], ''  ).strip()
str2

This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also



'This is practice data create!!d for text process11ing so @# ``- added some special charac22ters'

In [121]:
# remove 1st character from string
str2 = str1[1:]
str2
# remove last character from string
str2 = str1[:-1]
str2

'This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also'

In [148]:
# remove duplicate words from string
temp = "xyz abc abc ttt"
temp1 = temp.split()
str2 = sorted( set(temp1), key=temp1.index)
' '.join(str2)

'xyz abc ttt'

In [157]:
# count of a word in string
strx
len([x for x in strx.split() if x=='pqr'])

2

In [ ]:
# sub-string count in string
print(strx)
strx.count('pq')

In [159]:
# count of all words in string
print(strx) # 
strx_unique = sorted(set(strx.split()), key=strx.index)
print(strx_unique)
def word_freq(str_xx):
    return(len([x for x in strx.split() if x==str_xx]))
words_freq_list = [word_freq(x) for x in strx_unique]
print(words_freq_list)

xyz abc ttt ttt pqr pqr pqt hhu huz
['xyz', 'abc', 'ttt', 'pqr', 'pqt', 'hhu', 'huz']
[1, 1, 2, 2, 1, 1, 1]


In [190]:
# get sub-string between 2 sub-strings ('abc' & 'pqt')
print(strx) # 'xyz abc ttt ttt pqr pqr pqt hhu huz'
start_index = [x+3 for x in range(len(strx)) if 'abc' in strx[x:x+3]]
print(start_index)
end_index = [x+3 for x in range(len(strx)) if 'pqt' in strx[x:x+3]]
print(end_index)
print(strx[start_index[0]:end_index[0]-3])
# OR
result = re.search('abc(.*)pqr', strx)
str(result.group(1))

xyz abc ttt ttt pqr pqr pqt hhu huz
[7]
[27]
 ttt ttt pqr pqr 


' ttt ttt pqr '

In [221]:
# split text variable of df into 2 using 'delimiter'
import pandas as pd 
data = [['tom-x', 10, 6.1], ['nick-y', 15, 5.8], ['arnold-t', 11, 5.6], ['sam-g', 13, 5.7]] 
dff = pd.DataFrame(data, columns = ['Name', 'Age', 'Height']) 
print(dff)
dff['Name_first'] = dff['Name'].apply(lambda x: x.split('-')[0])
dff['Name_last'] = dff['Name'].apply(lambda x: x.split('-')[1])
print(dff)

       Name  Age  Height
0     tom-x   10     6.1
1    nick-y   15     5.8
2  arnold-t   11     5.6
3     sam-g   13     5.7
       Name  Age  Height Name_first Name_last
0     tom-x   10     6.1        tom         x
1    nick-y   15     5.8       nick         y
2  arnold-t   11     5.6     arnold         t
3     sam-g   13     5.7        sam         g


In [229]:
# get last 4 characters of string
print(strx)
strx[len(strx)-4:len(strx)]

xyz abc ttt ttt pqr pqr pqt hhu huz


' huz'

In [ ]:
## Regex - more

In [628]:
# find matching sub-string in string
print(strx)
if (re.search('pqr', strx)):
    print('match found')

# find sub-string location in string:
temp = 'sphinx..=.=221'
result = re.search("=", temp)
print(result.span(0)[0]) # output=6 (1st location)

xyz abc ttt ttt pqr cqr pqt hhx hxxz
match found
8


In [440]:
# find words starting with a character/s
print(strx)
temp = re.findall(r'\b(h\w+)', strx) 
# \b(h\w+) searches for 'h+chars' at start of word
# r'\b[sS]\w+' for lower & upper case
# \b searches for at start or end dep on placement in query
print(temp)
# can use 'startswith' also, as above

xyz abc ttt ttt pqr cqr pqt hhx hxxz
['hhx', 'hxxz']


In [442]:
# find words ending with a character/s
print(strx)
temp = re.findall(r'(\w+z)\b',strx) 
# (\w+z)\b searches for '\w+z' at start of word
# \b searches for at start or end dep on placement in query
print(temp)
# can use 'endswith' also, as above

xyz abc ttt ttt pqr cqr pqt hhx hxxz
['xyz', 'hxxz']


In [445]:
# find words with sub-string at center (not searching at ends)
print(strx)
temp = re.findall(r'(\w+q\w+)', strx)
print(temp)

xyz abc ttt ttt pqr cqr pqt hhx hxxz
['pqr', 'cqr', 'pqt']


In [619]:
# Check lower case / upper case:
str_temp = 'AbcXyz'
print(str_temp.isupper())
print(str_temp.islower())
# Convert to lower case / upper case:
print(str_temp.upper())
print(str_temp.lower())

False
False
ABCXYZ
abcxyz


In [618]:
str1

'This is practice data create!!d for text process11ing so @# ``- added some special charac22ters also\n'

####################################################
############## For Loops
####################################################

In [251]:
# for loop
for i in range(len(strx.split())):
#     print(i)
    pass
for word in strx.split():
#     print(word)
    pass
for i,j in enumerate(strx.split()):
#     print("{} is index, {} is word".format(i,j))
    pass

x1 = [7,5,4]
x2 = [77,55,44]
for j,k in zip(x1,x2):
#     print("{}-{}".format(j,k))
    pass
for i,(j,k) in enumerate(zip(x1,x2)):
#     print("{}-{}-{}".format(i,j,k))
    pass
    
x1 = {'key1':3, 'key2':6}
for key in x1.keys():
    print("{k}-{v}".format(k=key, v=x1[key]))
for key,value in x1.items():
    print("{k}-{v}".format(k=key, v=value))

key1-3
key2-6
key1-3
key2-6


####################################################
############## List, Tuple, Set Operations
####################################################

In [252]:
# list comprehensions & for loops are covered

In [336]:
list1 = [5, -3, 77, 1, 77, 34]
list2 = ['xx', 're', 'xx', 'tt', 'wq']
list3 = [1, 44, 'test', 'exam', 65.0]
list4 = [(9, '10', 4.3),
                (7, '17', 2.5),
                (15, '39', 11.4)]
tup1 = (5, 3, 77, 1, 77, 34)
tup2 = ('xx', 're', 'xx', 'tt', 'wq')
tup3 = (1, 44, 'test', 'exam', 65.0)
set1 = {4, 55, 6, 7}
set2 = {4, 55, 'xyz', 7, 'abc'}

In [320]:
# remove duplicates
print(list1)
temp = sorted(set(list1), key=list1.index)
print(temp)

[5, -3, 77, 1, 77, 34]
[5, -3, 77, 1, 34]


In [307]:
# sort 'list of tuples' by 1st element of tuples
list4_val1 =  [x[0] for x in list4]  # [9, 7, 15]
list4_dict = {k:v for (k,v) in zip(list4_val1,list4)}
list4_key_sort = sorted(list4_dict)
list_sort = [list4_dict[x] for x in list4_key_sort]
list_sort
# OR
temp = list4.copy()
temp.sort(key=lambda x: x[0])
temp

[(7, '17', 2.5), (9, '10', 4.3), (15, '39', 11.4)]

In [316]:
# append value in tuple
print(tup1)
tup1_list = list(tup1)
tup1_list.append(99)
temp = tuple(tup1_list)
print(temp)

(5, 3, 77, 1, 77, 34)
(5, 3, 77, 1, 77, 34, 99)


In [323]:
# remove negative values from list
print(list1)
temp = [x for x in list1 if x>=0]
print(temp)

[5, -3, 77, 1, 77, 34]
[5, 77, 1, 77, 34]


In [328]:
# remove last element of list
print(list1)
temp = list1.copy()
temp.pop()
print(temp)

[5, -3, 77, 1, 77, 34]
[5, -3, 77, 1, 77]


In [349]:
# add element to set
print("set1-{}".format(set1))
temp = set1.copy()
temp.add(99)
print(temp)
# remove element to set
temp = set1.copy()
temp.remove(55)
print(temp)

# intersection of 2 sets
print("------------")
print("set1-{}".format(set1))
print("set2-{}".format(set2))
temp1 = set1.copy()
temp2 = set2.copy()
temp = temp1.intersection(temp2)
print(temp)
# union of 2 sets
temp = temp1.union(temp2)
print(temp)

set1-{4, 7, 6, 55}
{99, 4, 6, 7, 55}
{4, 7, 6}
------------
set1-{4, 7, 6, 55}
set2-{4, 7, 'abc', 55, 'xyz'}
{4, 55, 7}
{4, 6, 7, 'abc', 55, 'xyz'}


In [360]:
# subtract 2 lists
print(list1)
print(list3)
diff = list( set(list1).intersection(set(list3)) ) # find intersection
temp = [x for x in list1 if x not in diff] # find difference
print(temp)

[5, -3, 77, 1, 77, 34]
[1, 44, 'test', 'exam', 65.0]
[5, -3, 77, 77, 34]


####################################################
############## Dictionary Operations
####################################################

In [467]:
# Note: Dict is unordered(for faster search) and keys are unique

In [464]:
d_simple1 = {"name":"Ford Prefect", "gender":"male"}
d_simple2 = {"age":40, 'height':5.7}
d_complex = {   
    "players": [
        {
            "name": "Virat Kohli",
            "gender": "male"
        },
        {
            "name": "Rohit Sharma",
            "gender": "male"
        },
        {
            "name": "Jasprit Bumrah",
            "gender": "male"
        }   
    ]
}

In [465]:
# access dict values using keys
print(d_simple['name'])
print(d_simple.get('name'))

Ford Prefect
Ford Prefect


In [466]:
# create dict(list) using defaultdict
from collections import defaultdict
d1 = defaultdict(list)
d1['name'].append('Tim')
d1['name'].append('Jim')
d1['age'].append(40)
d1

defaultdict(list, {'name': ['Tim', 'Jim'], 'age': [40]})

In [471]:
# append dict to dict
import copy
temp = copy.deepcopy(d_simple1)
temp.update(d_simple2)
temp

{'name': 'Ford Prefect', 'gender': 'male', 'age': 40, 'height': 5.7}

In [576]:
# combine the 2 dicts the way it's shown in output
d1 = {1: 23, 2: 76, 4: 56, 5: 77}
d2 = {23: 'a', 76: 'b', 56: 'c', 99: 'd'}
# output: {1: [23, 'a'], 2: [76, 'b'], 4: [56, 'c']}

d3 = defaultdict(list)
for key1, key2 in zip(d1.keys(), d2.keys()):
    if d1[key1] == key2:
        d3[key1].append(d1[key1])
        d3[key1].append(d2[key2])
d3

# OR
temp = { k:[v,d2[v]] for (k,v) in zip(d1.keys(), d1.values()) if v in d2.keys()}
temp

{1: [23, 'a'], 2: [76, 'b'], 4: [56, 'c']}

In [493]:
# get top n keys of dict
list(d_simple1.keys())[0:2]

['name', 'gender']

In [506]:
# observe this behaviour by keeping/removing global
dict1 = {}
dict2 = {}
dict2['abc'] = "xyz"
def abc():
    global dict1 # 'global' to be used like this in Python 
    # https://www.geeksforgeeks.org/global-keyword-in-python/
    dict1 = dict2
abc()
print (dict1)

{'abc': 'xyz'}


In [499]:
# observe this behaviour (contd..)
dict11 = {}
def abc():
    # global dict1 # not required her 
    dict11['xyz'] = 5
abc()
print (dict11)

{'xyz': 5}


####################################################
############## Numpy & Matrix Operations
####################################################

In [530]:
# create 1D and 2D numpy arrays
np1 = np.zeros([6], dtype=int)
np1[1] = 43
np1[3] = 65
np1[4] = 11
print(np1)
np2 = np.zeros([4,4], dtype=int)
np2[0][0] = 34
np2[0][2] = 43
np2[1][2] = 75
np2[2][1] = 2
print(np2)

[ 0 43  0 65 11  0]
[[34  0 43  0]
 [ 0  0 75  0]
 [ 0  2  0  0]
 [ 0  0  0  0]]


In [578]:
# create matrix from 2D array
m1 = np.asmatrix(np2)
m1

matrix([[34,  0, 43,  0],
        [ 0,  0, 75,  0],
        [ 0,  2,  0,  0],
        [ 0,  0,  0,  0]])

In [531]:
# convert array type to float
temp = np1.astype(float)
temp

array([ 0., 43.,  0., 65., 11.,  0.])

In [582]:
# check array shape
print(np2.shape)
print(np2.shape[0])
# reshape array
temp = np.reshape(np2, (2,8))
print(temp)

(4, 4)
4
[[34  0 43  0  0  0 75  0]
 [ 0  2  0  0  0  0  0  0]]


In [571]:
# concatenate 2 arrays (1D) - horizontally
temp = np.concatenate([np1, np2.flatten()], axis=0)
temp
# concatenate 2 arrays (2D) - vertically
print(np2)
temp = np.concatenate([np2, np2], axis=1)
print(temp)

[[34  0 43  0]
 [ 0  0 75  0]
 [ 0  2  0  0]
 [ 0  0  0  0]]
[[34  0 43  0 34  0 43  0]
 [ 0  0 75  0  0  0 75  0]
 [ 0  2  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [564]:
# append value/array to numpy array
temp = np.append(np1, 99)
temp
temp = np.append(np1, np1)
temp

array([ 0, 43,  0, 65, 11,  0,  0, 43,  0, 65, 11,  0])

In [575]:
# remove value/array from numpy array
print(np1)
t1 = np1[0:2]
print(t1)
temp = np.setdiff1d(np1, t1)
print(temp)

[ 0 43  0 65 11  0]
[ 0 43]
[11 65]


In [555]:
# create 2D array from 1D arrays:
temp = np.array([np1, np1])
temp

array([[ 0, 43,  0, 65, 11,  0],
       [ 0, 43,  0, 65, 11,  0]])

In [559]:
# transpose array
print(np2)
print(np2.T)

[[34  0 43  0]
 [ 0  0 75  0]
 [ 0  2  0  0]
 [ 0  0  0  0]]
[[34  0  0  0]
 [ 0  0  2  0]
 [43 75  0  0]
 [ 0  0  0  0]]


In [561]:
# access 1st column of 2D array
np2[:,0]
# access 1st row of 2D array
np2[0,:]

array([34,  0, 43,  0])

####################################################
############## Others
####################################################

In [596]:
# create dataframe
import pandas as pd 
data = [['tom', 10, '23-12-1983'], ['nick', 15, '25-7-1999'], 
        ['julie', 14, '26-11-1985'], ['annie', 18, '12-3-1978']]
df = pd.DataFrame(data, columns = ['Name', 'Age', 'Date']) 
print(df)

    Name  Age        Date
0    tom   10  23-12-1983
1   nick   15   25-7-1999
2  julie   14  26-11-1985
3  annie   18   12-3-1978


In [597]:
# convert string column to date type
import datetime
df['Date'] = pd.to_datetime(df['Date'])
df['Date']

0   1983-12-23
1   1999-07-25
2   1985-11-26
3   1978-12-03
Name: Date, dtype: datetime64[ns]

In [598]:
# get year/month/day info from date variable
df['Date'].dt.year
df['Date'].dt.month
df['Date'].dt.day

0    23
1    25
2    26
3     3
Name: Date, dtype: int64

In [602]:

temp = df.copy()
temp.index = temp['Date']
temp['1999']

Name  Age       Date
Date                            
1999-07-25  nick   15 1999-07-25

In [604]:
temp = df.loc[df['Date']>'1980-07-24', :]
temp

Name  Age       Date
0    tom   10 1983-12-23
1   nick   15 1999-07-25
2  julie   14 1985-11-26

In [616]:
df

Name  Age       Date
0    tom   10 1983-12-23
1   nick   15 1999-07-25
2  julie   14 1985-11-26
3  annie   18 1978-12-03