### Anaconda & Python Version:

The version of the notebook server is 5.0.0 and is running on:
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]

Current Kernel Information:
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

#### Anaconda 5.0.1

In [323]:
#########################################################################
####### Text Classification (Only Text, no other variables used) -  1 CPU
#########################################################################

In [9]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import numpy as np  
import re  # regular expressions like '+', '*'
import nltk  # The Natural Language Toolkit
from sklearn.datasets import load_files  
# nltk.download('popular') 
# will download stopwords, punkt etc # download in default dir else error later on
import pickle  
from nltk.corpus import stopwords
from nltk import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [10]:
# Ref: https://www.analyticsvidhya.com/blog/2018/04/a-comprehensive-guide-to-understand-and-implement-text-classification-in-python/

In [11]:
# importing data
# Windows 
# hollybolly_inc=pd.read_excel("C:/Users/anurag.trivedi/Dropbox/Job 06 Sep 2018/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly Increased.xlsx",sheet_name='HollyBolly Increased')
# Linux
hollybolly_inc=pd.read_csv("/home/antrived/Dropbox/Job-25-Feb-2019/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly_Increased_V2.csv", encoding='ISO-8859-1')
hollybolly = hollybolly_inc
hollybolly.head(10)

Industry                                          Wiki_Text
0  Hollywood  is a neighborhood in the central region of Los...
1  Hollywood  including several of its historic studios. Its...
2  Hollywood  ethnically diverse, densely populated, economi...
3  Hollywood  Hollywood was a small community in 1870 and wa...
4  Hollywood  1910, and soon thereafter a prominent film in...
5  Hollywood  In 1853, one adobe hut stood in Nopalera (No...
6  Hollywood  community flourished. The area was known as th...
7  Hollywood  According to the diary of H. J. Whitley, kno...
8  Hollywood  carrying wood. The man got out of the wagon an...
9  Hollywood  represent England and wood would represent his...

In [12]:
hollybolly.Industry[hollybolly.Industry == "Hollywood"] = 1
hollybolly.Industry[hollybolly.Industry == "Bollywood"] = 0

In [13]:
Y = hollybolly.iloc[:,0].values
type(Y) # numpy array
Y
# sum(hollybolly.Industry)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [14]:
X = hollybolly.iloc[:,1].values.tolist() 
print(type(X)) # X is list
print(X)

<class 'list'>
['is a neighborhood in the central region of Los Angeles, California. The neighborhood is notable for its place as the home of the U.S. film industry, ', 'including several of its historic studios. Its name has come to be aÂ\xa0metonymfor theÂ\xa0motion picture industry of the United States. Hollywood is also a highlyÂ\xa0', 'ethnically diverse, densely populated, economically diverse neighborhood and retail business district.', 'Hollywood was a small community in 1870 and was incorporated as a municipality in 1903.[3][4]Â\xa0It officially merged with the city of Los Angeles inÂ\xa0', '1910, and soon thereafter a prominentÂ\xa0film industryÂ\xa0began to emerge, eventually becoming the most recognizable film industry in the world.[5][6]', 'In 1853, oneÂ\xa0adobeÂ\xa0hut stood in Nopalera (NopalÂ\xa0field), named for the MexicanÂ\xa0Nopal cactusÂ\xa0indigenous to the area. By 1870, an agriculturalÂ\xa0', 'community flourished. The area was known as theÂ\xa0Cahuenga Valley,

In [15]:
## Cleaning - run either Clean1 or Clean2

In [16]:
# Clean1 (run either Clean1 or Clean2)
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # removes unicode characters

    
def remove_stopwords(sentence):
    stop_words = set(stopwords.words("english"))
    return " ".join([word.lower() for word in word_tokenize(sentence)
                    if word.lower() not in stop_words and word.isalpha()])


def clean_stopw_more(text1):
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # works on list of strings
    documents = []
    for sen in text1:
        documents.append(remove_stopwords(sen))
    return documents


def clean_unicode(text1):
    # removes unicode characters
    # works on list of strings
    documents = []
    for sen in text1:
        sen = str(sen.encode('ascii','ignore'))
        sen = sen[2:]
        sen = sen[:-1]
        sen = " ".join(sen.split())
        documents.append(remove_stopwords(sen))
    return documents

# Lemmatize with POS Tag
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)


def lemmatize(text1):
    # lemmitizes
    # works on list of strings
    documents = []
    lemmatizer = WordNetLemmatizer() 
    for sen in text1:      
        document = ""
        for word in sen.split():
#             word1 = lemmatizer.lemmatize(word) # only removes 's' at the end of nouns as of now
#             word1 = lemmatizer.lemmatize(word, pos ="a") # also converts adjective 'better' to 'good'
            word1 = lemmatizer.lemmatize(word, get_wordnet_pos(word)) # as per word's POS tag
            document = (''.join(document+" "+word1)).strip()
        documents.append(document)
    return documents


def stem(text1):
    # lemmitizes
    # works on list of strings
    ps = PorterStemmer()
    documents = []
    for sen in text1:
        words = word_tokenize(sen)
        document = []
        for w in words:
            document.append(ps.stem(w)) # can try other stemming algos to improve accuracy
        document = ' '.join(document)
        documents.append(document)
    return documents


X = clean_stopw_more(X)
X = clean_unicode(X)
X = lemmatize(X)
print(X)

['neighborhood central region los angeles california neighborhood notable place home film industry', 'include several historic studio name come metonymfor motion picture industry united state hollywood also highly', 'ethnically diverse densely populate economically diverse neighborhood retail business district', 'hollywood small community incorporate municipality officially merge city los angeles', 'soon thereafter prominent film industry begin emerge eventually become recognizable film industry world', 'one adobe hut stood nopalera nopal field name mexican nopal cactus indigenous area agricultural', 'community flourish area know cahuenga valley pas santa monica mountain immediately north', 'accord diary whitley know father hollywood honeymoon stood top hill look valley along come chinese man wagon', 'carry wood man get wagon bow chinese man ask reply meaning wood whitley epiphany decide name new town hollywood holly would', 'represent england wood would represent scottish heritage whi

In [215]:
# # Clean2: (run either Clean1 or Clean2)
# # Generic_Cleaning (without stop_words removal) and Stemming / Lemmitization

# def clean_generic(text1):
#     # cleans but does not remove stop_words
#     # works on list of strings

#     documents = []
#     ps = PorterStemmer() 

#     for sen in range(0, len(text1)):  

#         # Remove all the special characters
#         document = re.sub(r'\W', ' ', str(X[sen]))
#         # Remove "_"
#         document = document.replace("_", " ")
#         # remove unicode characters
#         document = str(document.encode('ascii','ignore'))
#         document = document[1:]
#         document = document[1:]
#         document = document[:-1]
#         # remove all numerics
#         document=''.join(c if c not in map(str,range(0,10)) else "" for c in document)
#         # remove all extra spaces
#         document = " ".join(document.split())
#     #     # Remove single characters from the start
#     #     document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
#     #     # remove all single characters
#     #     document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
#         # Converting to Lowercase
#         document = document.lower()

#     #     # Substituting multiple spaces with single space
#     #     document = re.sub(r'\s+', ' ', document, flags=re.I)
#     #     # remove leading and trailing spaces
#     #     document = document.strip()

#     #     # Stemming:
#     #     words = word_tokenize(document)
#     #     document = []
#     #     for w in words:
#     #         document.append(ps.stem(w)) # can try other stemming algos to improve accuracy
#     #     document = ' '.join(document)
#     #     # Note: this stemming code converted 'los angeles' to 'lo angel' so maybe not good

#     #     # Lemmatization:
#         stemmer = WordNetLemmatizer()
#         document = document.split()
#         document = [stemmer.lemmatize(word) for word in document]
#         document = ' '.join(document)
#         document

#         documents.append(document)
        
#     return documents

# X = clean_generic(X)
# print(X)

['is a neighborhood in the central region of los angeles california the neighborhood is notable for it place a the home of the u s film industry', 'including several of it historic studio it name ha come to be a metonymfor the motion picture industry of the united state hollywood is also a highly', 'ethnically diverse densely populated economically diverse neighborhood and retail business district', 'hollywood wa a small community in and wa incorporated a a municipality in it officially merged with the city of los angeles in', 'and soon thereafter a prominent film industry began to emerge eventually becoming the most recognizable film industry in the world', 'in one adobe hut stood in nopalera nopal field named for the mexican nopal cactus indigenous to the area by an agricultural', 'community flourished the area wa known a the cahuenga valley after the pas in the santa monica mountain immediately to the north', 'according to the diary of h j whitley known a the father of hollywood on 

In [66]:
## TF-IDF and Train-Test Split

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer  
# tfidfconverter = TfidfVectorizer(max_features=1500, min_df=1, max_df=0.9, stop_words=stopwords.words('english'))
tfidfconverter = TfidfVectorizer(max_features=1500, ngram_range=(1, 2), stop_words=stopwords.words('english'))
# df = document frequency (min_df seems to be auto divided by 100)
# X = tfidfconverter.fit_transform(documents).toarray()  

In [101]:
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=12) 
Y_train = Y_train.astype(int)
Y_test = Y_test.astype(int)
# len(X_train) # 128
# len(X_test) # 32

In [102]:
tfidfconverter.fit(X)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1500, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs',... 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"],
        strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [103]:
X_train = tfidfconverter.transform(X_train)
print(X_train)
# X_train_tfidf = pd.DataFrame(X_train_tfidf)
X_test = tfidfconverter.transform(X_test)
print(X_test)
# X_test_tfidf = pd.DataFrame(X_test_tfidf)

  (0, 1342)	0.2779024329806928
  (0, 1340)	0.24254835223646679
  (0, 1184)	0.25722162149785266
  (0, 1120)	0.2779024329806928
  (0, 1119)	0.2779024329806928
  (0, 1111)	0.2779024329806928
  (0, 1110)	0.2779024329806928
  (0, 933)	0.2779024329806928
  (0, 265)	0.25722162149785266
  (0, 252)	0.25722162149785266
  (0, 249)	0.25722162149785266
  (0, 200)	0.21400506113279397
  (0, 198)	0.23116688037598412
  (0, 10)	0.3374960447926617
  (1, 1495)	0.24124377075591213
  (1, 1494)	0.2001046172765391
  (1, 1476)	0.21285400388204578
  (1, 1443)	0.27640769445072644
  (1, 1442)	0.27640769445072644
  (1, 1370)	0.27640769445072644
  (1, 1365)	0.17769008018723143
  (1, 820)	0.27640769445072644
  (1, 819)	0.27640769445072644
  (1, 514)	0.27640769445072644
  (1, 511)	0.2558381177110399
  :	:
  (117, 1193)	0.38431964720769346
  (117, 1192)	0.38431964720769346
  (117, 1170)	0.15341365326441084
  (117, 1157)	0.19215982360384673
  (117, 1156)	0.16771371189974874
  (117, 1063)	0.19215982360384673
  (117, 106

In [21]:
# export
# np.savetxt("/home/antrived/Dropbox/Job 25 Feb 2019/prep/x2-more new projects & new techniques/1. Techniques & Algos/10. Text Analytics and NLP/1. Text Classification and Word2Vec/Temp3.csv", X_train_tfidf, delimiter=",")

In [22]:
# export
# np.savetxt("/home/antrived/Dropbox/Job 25 Feb 2019/prep/x2-more new projects & new techniques/1. Techniques & Algos/10. Text Analytics and NLP/1. Text Classification and Word2Vec/Temp4.csv", X_test_tfidf, delimiter=",")

In [23]:
# display X, Y as df

# X_df = pd.DataFrame(X)
# X_df.head(5)

In [24]:
# export
# np.savetxt("/home/antrived/Dropbox/Job 25 Feb 2019/prep/x2-more new projects & new techniques/1. Techniques & Algos/10. Text Analytics and NLP/1. Text Classification and Word2Vec/Temp1.csv", X, delimiter=",")

In [104]:
# Import classification related packages
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import classification_report

In [105]:
############# Random Forest ###############

In [106]:
from sklearn.ensemble import RandomForestClassifier

In [107]:
# Training
def rf_classifier(X_train, Y_train, n_estimators, max_depth, max_features, random_state):
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features, random_state=random_state)   
    Y_train = np.asarray(Y_train, dtype="|S6")
    model.fit(X_train, Y_train)
    return model

def rf_predictions(model, X_test, Y_test):
    y_pred = model.predict_proba(X_test) # default 'predict' gives 'categorical' predictions for RF
    # classifier.classes_ # to check order of classes in 'predict_proba' (most prob. it's 0,1...)
    y_pred = y_pred[:,1] # accessing 2nd column or '1' class probabilities
    # converting prob to 1/0 and array type to int
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred
    
def create_reports(y_pred, Y_test):
    # creating CF matrix
    Y_test = Y_test.astype(int)
    y_pred = y_pred.astype(int)
    cm1 = confusion_matrix(y_pred, Y_test)
    print("\n--Confusion Matrix--\n")
    print(cm1)
    # calculating auc
    fp_rate, tp_rate, thresholds = roc_curve(Y_test, y_pred)
    print("\n-------AUC-------\n")
    print(auc(fp_rate, tp_rate))
    print("\n----------------Classification_Report------------------\n")
    print(classification_report(Y_test, y_pred))

In [192]:
model = rf_classifier(X_train, Y_train, n_estimators=100, max_depth=7, max_features=400, random_state=0)
y_pred = rf_predictions(model, X_test, Y_test) # tabular: model.predict works with test_df
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 20]
 [ 0  4]]

-------AUC-------

0.5833333333333334

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.57      1.00      0.73        27
           1       1.00      0.17      0.29        24

   micro avg       0.61      0.61      0.61        51
   macro avg       0.79      0.58      0.51        51
weighted avg       0.77      0.61      0.52        51



In [109]:
############# Saving/Loading Model & Scoring ###############

In [110]:
## Saving model
with open('./saved_models/text_classifier_RF', 'wb') as picklefile:  
    pickle.dump(model,picklefile)

In [111]:
## Loading model
with open('./saved_models/text_classifier_RF', 'rb') as training_model:  
    model_rf = pickle.load(training_model)

In [115]:
# Scoring:
# text_scoring = ['Shahrukh khan is a big star in the b-town'] # predicts bolly
text_scoring = ['los angeles california'] # predicts holly

In [116]:
def score(text1):
# cleaning and shaping
    text1 = clean_stopw_more(text1)
    text1 = clean_unicode(text1)
    text1 = lemmatize(text1)
    X_Score = tfidfconverter.transform(text1)
    # scoring:
    pred = model.predict_proba(X_Score)
    pred = pred[:,1]
    pred[pred > 0.5] = 1
    pred[pred <= 0.5] = 0
    pred = pred[0].astype('int')
    return pred

In [117]:
pred = score(text_scoring)
pred # bolly=0, holly=1

1

In [589]:
############# Linear SVM ###############

In [153]:
from sklearn.svm import SVC 

In [176]:
# Training
def svm_classifier(X_train, Y_train, kernel, C, gamma):
    model = SVC(kernel=kernel, C=C, gamma=gamma) # kernel = rbf/linear 
    model.fit(X_train, Y_train) 
    return model

def common_predictions(model, X_test, Y_test):
    y_pred = model.predict(X_test)
    y_pred = y_pred.astype(int)
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred

In [183]:
model = svm_classifier(X_train, Y_train, kernel='linear', C=100, gamma=1)
y_pred = common_predictions(model, X_test, Y_test) # tabular: model.predict works with test_df
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 16]
 [ 0  8]]

-------AUC-------

0.6666666666666666

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.63      1.00      0.77        27
           1       1.00      0.33      0.50        24

   micro avg       0.69      0.69      0.69        51
   macro avg       0.81      0.67      0.64        51
weighted avg       0.80      0.69      0.64        51



In [322]:
############# Non-linear SVM ###############

In [156]:
model = svm_classifier(X_train, Y_train, kernel='rbf', C=10, gamma=0.1)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 16]
 [ 0  8]]

-------AUC-------

0.6666666666666666

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.63      1.00      0.77        27
           1       1.00      0.33      0.50        24

   micro avg       0.69      0.69      0.69        51
   macro avg       0.81      0.67      0.64        51
weighted avg       0.80      0.69      0.64        51



In [328]:
############# Naive Bayes ###############

In [157]:
from sklearn.naive_bayes import GaussianNB

In [158]:
# Training
def nb_classifier(X_train, Y_train):
    model = GaussianNB()
    temp = X_train.copy()
    model.fit(temp, Y_train)
    return model

In [159]:
if type(X_train) is not np.matrix:
    temp_X_train_ = X_train.toarray()
if type(X_test) is not np.matrix:
    temp_X_test_ = X_test.toarray() 
model = nb_classifier(temp_X_train_, Y_train)
y_pred = common_predictions(model, temp_X_test_, Y_test) 
# tabular: model.predict works with test_df; above 4 lines not needed
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[20  6]
 [ 7 18]]

-------AUC-------

0.7453703703703703

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.77      0.74      0.75        27
           1       0.72      0.75      0.73        24

   micro avg       0.75      0.75      0.75        51
   macro avg       0.74      0.75      0.74        51
weighted avg       0.75      0.75      0.75        51



In [127]:
############ LR ############

In [128]:
from sklearn.linear_model import LogisticRegression

In [131]:
# Training
def lr_classifier(X_train, Y_train, C):
    model = LogisticRegression(C=C) # Inverse of regularization strength
    model.fit(X_train, Y_train)
    return model

In [175]:
model = lr_classifier(X_train, Y_train, C=100)
y_pred = common_predictions(model, X_test, Y_test) 
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 17]
 [ 0  7]]

-------AUC-------

0.6458333333333334

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.61      1.00      0.76        27
           1       1.00      0.29      0.45        24

   micro avg       0.67      0.67      0.67        51
   macro avg       0.81      0.65      0.61        51
weighted avg       0.80      0.67      0.62        51



In [342]:
############ XGBoost #############

In [343]:
# Ref: https://www.kdnuggets.com/2017/03/simple-xgboost-tutorial-iris-dataset.html

In [133]:
# conda install -c conda-forge xgboost # some issues
# sudo pip install xgboost
from xgboost import XGBClassifier

In [134]:
# Training
def xgb_classifier(X_train, Y_train, max_depth, learning_rate, n_estimators, objective):
    model = XGBClassifier(max_depth=max_depth, learning_rate=learning_rate, n_estimators=n_estimators, objective=objective)
    model.fit(X_train, Y_train)
    return model

In [170]:
model = xgb_classifier(X_train, Y_train, max_depth=3, learning_rate=1.1, n_estimators=100, objective='binary:logistic')
y_pred = common_predictions(model, X_test, Y_test) # tabular: model.predict works with test_df
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[22 13]
 [ 5 11]]

-------AUC-------

0.6365740740740741

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.63      0.81      0.71        27
           1       0.69      0.46      0.55        24

   micro avg       0.65      0.65      0.65        51
   macro avg       0.66      0.64      0.63        51
weighted avg       0.66      0.65      0.63        51



In [351]:
############ ANN #############

In [136]:
# importing keras libraries and packages:
import keras
from keras.models import Sequential # to initialize the ANN
from keras.layers import Dense # to create layers of ANN
from keras.layers import Dropout

Using TensorFlow backend.


In [137]:
# Creating Basic ANN

np.random.seed(100) # works. gives close results on repeating but not exactly same.

# Initializing ANN
model = Sequential()

i = 0.25

# Adding input layer and 1st hidden layer
model.add(Dense(activation="relu", input_dim=1500, units=125, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
# Adding 2nd hidden layer
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# # model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# # model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# # model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# # model.add(Dropout(rate=i))
# model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=125, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=100, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=70, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=7, kernel_initializer="uniform"))
# # Adding hidden layer

# Adding output layer
model.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN (means run SGD on ANN)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting ANN to training set
model.fit(X_train, Y_train, batch_size=5, epochs=40)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/40
119/119 [==============================] - 1s 5ms/step - loss: 0.6921 - acc: 0.5630
Epoch 2/40
119/119 [==============================] - 0s 790us/step - loss: 0.6874 - acc: 0.6134
Epoch 3/40
119/119 [==============================] - 0s 829us/step - loss: 0.6805 - acc: 0.6134
Epoch 4/40
119/119 [==============================] - 0s 859us/step - loss: 0.5693 - acc: 0.6134
Epoch 5/40
119/119 [==============================] - 0s 1ms/step - loss: 0.2880 - acc: 0.6134
Epoch 6/40
119/119 [==============================] - 0s 802us/step - loss: 0.2356 - acc: 0.9580
Epoch 7/40
119/119 [==============================] - 0s 912us/step - loss: 0.0065 - acc: 1.0000
Epoch 8/40
119/119 [==============================] - 0s 1ms/step - loss: 2.3598e-05 - acc: 1.0000
Epoch 9/40
119/119 [==============================] - 0s 1ms/step - loss: 2.2998e-07 - acc: 1.0000
Epoch 1

In [138]:
y_pred = common_predictions(model, X_test, Y_test) # tabular: model.predict works with test_df
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[22  5]
 [ 5 19]]

-------AUC-------

0.8032407407407407

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.81      0.81      0.81        27
           1       0.79      0.79      0.79        24

   micro avg       0.80      0.80      0.80        51
   macro avg       0.80      0.80      0.80        51
weighted avg       0.80      0.80      0.80        51



In [ ]:
## Summary(HollyBolly data - 160 rows):
# NB better than RF as its effective with less data
# NB less powerful than SVM and LR due to its oversimplicity
# LR behaving exactly like SVM (high correlation)
## Note: On changing Train-Test ratio and random seed, algo behavior changes;
# NB becomes best; SVM and XG becomes worse
# NB fluctuates highly on changing Train-Test ratio and random seed

## Algorithm Rank: NB/ANN, SVM/XG, LR, RF

# tf-idf best acc is from ANN - 0.8032 (due to high dimensionality)

In [ ]:
# APPENDIX

In [219]:
lemmatize(['recommending'])

['recommend']