Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.8
The server is running on this version of Python:
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]

Current Kernel Information:
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
#### Implement Embeddings and evaluate them using text classification
## Key Source - https://towardsdatascience.com/understanding-feature-engineering-part-4-deep-learning-methods-for-text-data-96c44370bbfa
## Algos implemented - Word2Vec, GloVe and FastText

In [ ]:
###### STEPS:

#### Embeddings Generation - Word2Vec
#### Embeddings Generation - Gensim-Word2Vec
#### Text Classification Accuracy - Gensim-Word2Vec

#### Embeddings Generation - GloVe
#### Text Classification Accuracy - GloVe

#### Embeddings Generation - FastText
#### Text Classification Accuracy - FastText

In [ ]:
###############################################################
################ Embeddings Generation - Word2Vec
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - Gensim-Word2Vec
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - Gensim-Word2Vec
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - GloVe
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - GloVe
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - FastText
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - FastText
###############################################################

In [1]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import numpy as np  
import re  # regular expressions like '+', '*'
import nltk  # The Natural Language Toolkit
from sklearn.datasets import load_files  
# nltk.download('popular') 
# will download stopwords, punkt etc # download in default dir else error later on
import pickle  
from nltk.corpus import stopwords
from nltk import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [2]:
## importing data
# Windows 
# hollybolly_inc=pd.read_excel("C:/Users/anurag.trivedi/Dropbox/Job 06 Sep 2018/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly Increased.xlsx",sheet_name='HollyBolly Increased')
# Linux
hollybolly_inc=pd.read_csv("/home/antrived/Dropbox/Job-25-Feb-2019/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly_Increased_V2.csv", encoding='ISO-8859-1')
hollybolly = hollybolly_inc
hollybolly.head(10)

Industry                                          Wiki_Text
0  Hollywood  is a neighborhood in the central region of Los...
1  Hollywood  including several of its historic studios. Its...
2  Hollywood  ethnically diverse, densely populated, economi...
3  Hollywood  Hollywood was a small community in 1870 and wa...
4  Hollywood  1910, and soon thereafter a prominent film in...
5  Hollywood  In 1853, one adobe hut stood in Nopalera (No...
6  Hollywood  community flourished. The area was known as th...
7  Hollywood  According to the diary of H. J. Whitley, kno...
8  Hollywood  carrying wood. The man got out of the wagon an...
9  Hollywood  represent England and wood would represent his...

In [3]:
## Labelling
hollybolly.Industry[hollybolly.Industry == "Hollywood"] = 1
hollybolly.Industry[hollybolly.Industry == "Bollywood"] = 0

In [4]:
Y = hollybolly.iloc[:,0].values
type(Y) # numpy array
Y
# sum(hollybolly.Industry)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [5]:
X = hollybolly.iloc[:,1].values.tolist() 
print(type(X)) # X is list
print(X)

<class 'list'>
['is a neighborhood in the central region of Los Angeles, California. The neighborhood is notable for its place as the home of the U.S. film industry, ', 'including several of its historic studios. Its name has come to be aÂ\xa0metonymfor theÂ\xa0motion picture industry of the United States. Hollywood is also a highlyÂ\xa0', 'ethnically diverse, densely populated, economically diverse neighborhood and retail business district.', 'Hollywood was a small community in 1870 and was incorporated as a municipality in 1903.[3][4]Â\xa0It officially merged with the city of Los Angeles inÂ\xa0', '1910, and soon thereafter a prominentÂ\xa0film industryÂ\xa0began to emerge, eventually becoming the most recognizable film industry in the world.[5][6]', 'In 1853, oneÂ\xa0adobeÂ\xa0hut stood in Nopalera (NopalÂ\xa0field), named for the MexicanÂ\xa0Nopal cactusÂ\xa0indigenous to the area. By 1870, an agriculturalÂ\xa0', 'community flourished. The area was known as theÂ\xa0Cahuenga Valley,

In [6]:
## Cleaning - run either Clean1 or Clean2

In [7]:
# Clean1 (run either Clean1 or Clean2)
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # removes unicode characters

    
def remove_stopwords(sentence):
    stop_words = set(stopwords.words("english"))
    return " ".join([word.lower() for word in word_tokenize(sentence)
                    if word.lower() not in stop_words and word.isalpha()])


def clean_stopw_more(text1):
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # works on list of strings
    documents = []
    for sen in text1:
        documents.append(remove_stopwords(sen))
    return documents


def clean_unicode(text1):
    # removes unicode characters
    # works on list of strings
    documents = []
    for sen in text1:
        sen = str(sen.encode('ascii','ignore'))
        sen = sen[2:]
        sen = sen[:-1]
        sen = " ".join(sen.split())
        documents.append(remove_stopwords(sen))
    return documents


# Lemmatize with POS Tag
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)


def lemmatize(text1):
    # lemmitizes
    # works on list of strings
    documents = []
    lemmatizer = WordNetLemmatizer() 
    for sen in text1:      
        document = ""
        for word in sen.split():
#             word1 = lemmatizer.lemmatize(word) # only removes 's' at the end of nouns as of now
#             word1 = lemmatizer.lemmatize(word, pos ="a") # also converts adjective 'better' to 'good'
            word1 = lemmatizer.lemmatize(word, get_wordnet_pos(word)) # as per word's POS tag
            document = (''.join(document+" "+word1)).strip()
        documents.append(document)
    return documents


X = clean_stopw_more(X)
X = clean_unicode(X)
X = lemmatize(X)
print(X)

['neighborhood central region los angeles california neighborhood notable place home film industry', 'include several historic studio name come metonymfor motion picture industry united state hollywood also highly', 'ethnically diverse densely populate economically diverse neighborhood retail business district', 'hollywood small community incorporate municipality officially merge city los angeles', 'soon thereafter prominent film industry begin emerge eventually become recognizable film industry world', 'one adobe hut stood nopalera nopal field name mexican nopal cactus indigenous area agricultural', 'community flourish area know cahuenga valley pas santa monica mountain immediately north', 'accord diary whitley know father hollywood honeymoon stood top hill look valley along come chinese man wagon', 'carry wood man get wagon bow chinese man ask reply meaning wood whitley epiphany decide name new town hollywood holly would', 'represent england wood would represent scottish heritage whi

In [2]:
from gensim.models.fasttext import FastText

In [ ]:
ft_model = FastText(tokenized_corpus, size=feature_size, window=window_context, 
                    min_count=min_word_count,sample=sample, sg=1, iter=50)

In [ ]:
###############################################################
################ Embeddings Generation - FastText
###############################################################

In [10]:
from gensim.models.fasttext import FastText

wpt = nltk.WordPunctTokenizer()
tokenized_corpus = [wpt.tokenize(document) for document in X]

# Set values for various parameters
feature_size = 100    # Word vector dimensionality  
window_context = 50          # Context window size                                                                                    
min_word_count = 1   # Minimum word count                        
sample = 1e-3   # Downsample setting for frequent words

# sg decides whether to use the skip-gram model (1) or CBOW (0)
ft_model = FastText(tokenized_corpus, size=feature_size, window=window_context, 
                    min_count=min_word_count,sample=sample, sg=1, iter=50)
# tune other params also like min_n, max_n
    # min_n : int, optional
    #     Minimum length of char n-grams to be used for training word representations.
    # max_n : int, optional
    #     Max length of char ngrams to be used for training word representations. Set `max_n` to be
    #     lesser than `min_n` to avoid char ngrams being used.
    # word_ngrams : {1,0}, optional
    #     If 1, uses enriches word vectors with subword(n-grams) information.
    #     If 0, this is equivalent to :class:`~gensim.models.word2vec.Word2Vec`.
                    
# view similar words based on gensim's FastText model
similar_words = {search_term: [item[0] for item in ft_model.wv.most_similar([search_term], topn=5)]
                  for search_term in ['los','bollywood','california','hollywood','voting','western','bengali','amitabh','bombay','blackbuck','baahubali']}
similar_words     

{'los': ['angeles', 'august', 'adequate', 'officially', 'secure'],
 'bollywood': ['ollywood', 'tollywood', 'hollywood', 'huge', 'portmanteau'],
 'california': ['griffith', 'quipped', 'gaga', 'deed', 'sorry'],
 'hollywood': ['ollywood', 'holly', 'tollywood', 'bollywood', 'dawood'],
 'voting': ['bribing', 'variety', 'fraud', 'disqualify', 'jury'],
 'western': ['mainstream', 'kamal', 'amrohi', 'scottish', 'united'],
 'bengali': ['bengal', 'parallel', 'recognition', 'benegal', 'mainly'],
 'amitabh': ['bachchan', 'jai', 'mukherjee', 'santoshi', 'helen'],
 'bombay': ['decease', 'fondness', 'sona', 'haji', 'married'],
 'blackbuck': ['rajasthan', 'poach', 'jodhpur', 'bishnoi', 'hearing'],
 'baahubali': ['demigod', 'pundit', 'endhiran', 'trade', 'box']}

In [11]:
def average_word_vectors(words, model, vocabulary, num_features):
    
    feature_vector = np.zeros((num_features,),dtype="float64")
    nwords = 0.
    
    for word in words:
        if word in vocabulary: 
            nwords = nwords + 1.
            feature_vector = np.add(feature_vector, model[word])
    
    if nwords:
        feature_vector = np.divide(feature_vector, nwords)
        
    return feature_vector
   
def averaged_word_vectorizer(corpus, model, num_features):
    vocabulary = set(model.wv.index2word)
    features = [average_word_vectors(tokenized_sentence, model, vocabulary, num_features)
                    for tokenized_sentence in corpus]
    return np.array(features)


# get document level embeddings
ft_feature_array = averaged_word_vectorizer(corpus=tokenized_corpus, model=ft_model,
                                             num_features=feature_size)
pd.DataFrame(ft_feature_array)

/home/antrived/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


0         1         2         3         4         5         6   \
0    0.901189 -0.429829  0.072537 -0.276152 -0.102324 -0.086483  0.191645   
1    0.695339 -0.254250 -0.171089  0.001380  0.190561  0.006520  0.066503   
2    0.431721 -0.501558 -0.125671 -0.229346  0.162066 -0.126459 -0.065437   
3    0.809112 -0.515515  0.111718 -0.023580 -0.199963 -0.033900  0.157925   
4    0.973768  0.072727 -0.182813  0.170368  0.078524 -0.044272  0.086718   
5    0.793502 -0.353642  0.035973 -0.067531 -0.160598  0.252447 -0.247286   
6    0.528605 -0.187904  0.225062 -0.067450  0.102634  0.231602 -0.177473   
7    0.780326 -0.186257  0.310420 -0.351271 -0.072221  0.469847  0.027111   
8    0.888432 -0.011046  0.291353 -0.142663 -0.245188  0.061572  0.030417   
9    0.666570 -0.122884  0.171197  0.128577 -0.245623 -0.069877  0.207662   
10   0.724431  0.084046  0.024213  0.151650  0.105990 -0.073179 -0.238586   
11   0.992306 -0.622992 -0.037546 -0.012552 -0.064725  0.159655  0.146614   
12   0.735475 -0.683696  0.353858 -0.099091 -0.389984  0.091399  0.076929   
13   0.764557 -0.483421 -0.013476 -0.097209  0.058227  0.165232  0.111806   
14   0.694002 -0.645488  0.126540 -0.111351 -0.198325 -0.020982  0.449097   
15   0.710222 -0.645607  0.188873 -0.157526 -0.106837  0.225218 -0.302224   
16   0.867346 -0.486642 -0.075895  0.239179 -0.189611  0.158737  0.171785   
17   0.730183 -0.332017  0.163964  0.023879 -0.173423 -0.015763  0.293534   
18   0.582446 -0.378028  0.097328  0.129944 -0.248229 -0.051842  0.243553   
19   0.722013 -0.172732  0.052162 -0.225157  0.080901  0.181035 -0.051066   
20   0.674128 -0.139736  0.022471 -0.215617 -0.053443  0.014383  0.198577   
21   0.365088 -0.390356 -0.094513 -0.144332  0.107592  0.026050 -0.416890   
22   0.742134 -0.557649  0.174629 -0.054127 -0.234820  0.035294  0.144151   
23   0.658875 -0.329375 -0.016084  0.139410 -0.310596 -0.065925  0.237145   
24   0.549006 -0.234354  0.012300 -0.057032 -0.245063 -0.065521 -0.079639   
25   0.741801 -0.739494  0.308562 -0.149341 -0.460031 -0.079378  0.084274   
26   0.779332 -0.473609 -0.083932  0.033362 -0.078407 -0.061510  0.265706   
27   0.777261  0.050743 -0.190158 -0.013344  0.135204 -0.145747  0.136261   
28   0.702403 -0.687170  0.272041  0.180767 -0.476761  0.085457 -0.121718   
29   1.007299 -0.081757 -0.226707 -0.113309  0.099967 -0.041301  0.282903   
..        ...       ...       ...       ...       ...       ...       ...   
140  0.312795 -0.146187  0.080841 -0.670533 -0.008729  0.393054 -0.114775   
141  0.378983 -0.251552  0.000814  0.236010 -0.118237  0.238249  0.021712   
142  0.636972 -0.253072  0.135902  0.064627 -0.064785  0.064222 -0.197405   
143  0.538338 -0.365483  0.076125 -0.185224  0.100967  0.155169 -0.252380   
144  0.597936 -0.358671  0.209767 -0.487063 -0.479696  0.256106 -0.140581   
145  0.467166 -0.392304  0.226427 -0.429604 -0.312853  0.066769 -0.493390   
146  0.554186 -0.288413 -0.102581 -0.389155 -0.035235 -0.175514 -0.326008   
147  0.677034 -0.047682  0.290770 -0.381469 -0.323120 -0.170329 -0.533560   
148  0.403216 -0.072065 -0.024274 -0.068782 -0.150847  0.222412  0.063613   
149  0.512254 -0.029711  0.131772  0.020333 -0.069355  0.292300 -0.382474   
150  0.717059 -0.160369 -0.011505  0.257515  0.128134  0.156203 -0.283288   
151  0.561271 -0.060034 -0.120531 -0.296043  0.255579  0.353040 -0.215581   
152  0.378120 -0.602076  0.130394  0.023939 -0.312931  0.118540 -0.308574   
153  0.387770 -0.221687  0.209432 -0.335965  0.012790  0.436755 -0.407993   
154  0.489335 -0.252099 -0.039114  0.045788 -0.039855  0.032530 -0.133718   
155  0.693385 -0.402935  0.272139 -0.044233 -0.503395  0.222822 -0.039136   
156  0.594991 -0.061909 -0.186384 -0.013950  0.140468  0.126185 -0.125579   
157  0.753932 -0.055446 -0.139433 -0.015887  0.115220 -0.131483  0.042237   
158  0.684723 -0.017150  0.152844 -0.006975  0.290961 -0.055462 -0.177096   
159  0.341456 -0.219856 -0.233426  0.016449  0.233355  0.051864 -0.591106   
160  0.

In [12]:
X = ft_feature_array

In [ ]:
###############################################################
################ Text Classification Accuracy - Glove-Word_Vectors
###############################################################

In [208]:
## Sampling

In [13]:
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=12)
Y_train = Y_train.astype(int)
Y_test = Y_test.astype(int)
# print(len(X_train)) # 119
# print(len(X_test)) # 51

In [14]:
X_train = np.asmatrix(X_train)
print(X_train)
X_test = np.asmatrix(X_test)
print(X_test)

[[ 0.38776971 -0.2216868   0.20943223 ...  0.12159078  0.40264293
  -0.00541164]
 [ 0.85644223  0.08876789 -0.29862993 ... -0.15438376  0.18732723
  -0.62196681]
 [ 0.78082934 -0.53663024  0.09740495 ...  0.0108951   0.38896559
  -0.12313614]
 ...
 [ 0.52820183 -0.3316175  -0.14240122 ...  0.03900575  0.26242312
  -0.02690729]
 [ 0.6933851  -0.40293498  0.27213865 ...  0.07936968  0.41606206
   0.32024485]
 [ 0.71700441 -0.26136195 -0.09686725 ...  0.0133314   0.22036277
  -0.18819032]]
[[ 0.85865485 -0.55311524  0.20650863 ... -0.3772923   0.29789165
  -0.18515526]
 [ 0.65887522 -0.32937474 -0.01608407 ... -0.15835804  0.13541921
   0.26924939]
 [ 0.53833791 -0.3654828   0.07612492 ...  0.42514542  0.42757055
  -0.18976219]
 ...
 [ 0.86270611  0.22517526 -0.20812471 ...  0.1236121   0.16589263
  -0.34491893]
 [ 0.54900582 -0.2343535   0.01229956 ... -0.01748444  0.12754433
   0.07137448]
 [ 0.72201277 -0.17273171  0.05216164 ... -0.26900962  0.03844724
  -0.0356634 ]]


In [15]:
# Import classification related packages
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import classification_report

In [16]:
############# Random Forest ###############

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
# Training
def rf_classifier(X_train, Y_train, n_estimators, max_depth, max_features, random_state):
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features, random_state=random_state)   
    Y_train = np.asarray(Y_train, dtype="|S6")
    model.fit(X_train, Y_train)
    return model

def rf_predictions(model, X_test, Y_test):
    y_pred = model.predict_proba(X_test) # default 'predict' gives 'categorical' predictions for RF
    # classifier.classes_ # to check order of classes in 'predict_proba' (most prob. it's 0,1...)
    y_pred = y_pred[:,1] # accessing 2nd column or '1' class probabilities
    # converting prob to 1/0 and array type to int
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred

## create binary classification report (multi-class not supported)
def create_reports(y_pred, Y_test):
    # creating CF matrix
    Y_test = Y_test.astype(int)
    y_pred = y_pred.astype(int)
    cm1 = confusion_matrix(y_pred, Y_test)
    print("\n--Confusion Matrix--\n")
    print(cm1)
    # calculating auc
    fp_rate, tp_rate, thresholds = roc_curve(Y_test, y_pred)
    print("\n-------AUC-------\n")
    print(auc(fp_rate, tp_rate))
    print("\n----------------Classification_Report------------------\n")
    print(classification_report(Y_test, y_pred))

In [28]:
model = rf_classifier(X_train, Y_train, n_estimators=300, max_depth=8, max_features=2, random_state=0)
y_pred = rf_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 15]
 [ 0  9]]

-------AUC-------

0.6875

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.64      1.00      0.78        27
           1       1.00      0.38      0.55        24

   micro avg       0.71      0.71      0.71        51
   macro avg       0.82      0.69      0.66        51
weighted avg       0.81      0.71      0.67        51



In [18]:
# Insight: Performance improved drastically over RF using regular text classification
    # refer: '9.1 Text Classification-One txt column' notebook

In [19]:
############# Linear/Non-Linear SVM ###############

In [29]:
from sklearn.svm import SVC 

In [86]:
# Training
def svm_classifier(X_train, Y_train, kernel, C, gamma):
    model = SVC(kernel=kernel, C=C, gamma=gamma) # kernel = rbf/linear 
    model.fit(X_train, Y_train) 
    return model

def common_predictions(model, X_test, Y_test):
    y_pred = model.predict(X_test)
    y_pred = y_pred.astype(int)
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred

In [100]:
model = svm_classifier(X_train, Y_train, kernel='rbf', C=20, gamma=0.2)
# model = svm_classifier(X_train, Y_train, kernel='linear', C=15, gamma=0.2)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[25  7]
 [ 2 17]]

-------AUC-------

0.8171296296296298

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.78      0.93      0.85        27
           1       0.89      0.71      0.79        24

   micro avg       0.82      0.82      0.82        51
   macro avg       0.84      0.82      0.82        51
weighted avg       0.83      0.82      0.82        51



In [319]:
# Insight: performance of SVM dipped by using word2vec
    # because number of vars have reduced from 1500 to 100 and N performs well with more vars
    # refer: '9.1 Text Classification-One txt column' notebook

In [320]:
############# Naive Bayes ###############

In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
# Training
def nb_classifier(X_train, Y_train):
    model = GaussianNB()
    temp = X_train.copy()
    model.fit(temp, Y_train)
    return model

In [54]:
model = nb_classifier(X_train, Y_train)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[22 12]
 [ 5 12]]

-------AUC-------

0.6574074074074074

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.65      0.81      0.72        27
           1       0.71      0.50      0.59        24

   micro avg       0.67      0.67      0.67        51
   macro avg       0.68      0.66      0.65        51
weighted avg       0.67      0.67      0.66        51



In [82]:
# Insight: performance of NB dipped by using word2vec
    # because number of vars have reduced from 1500 to 100 and N performs well with more vars
    # refer: '9.1 Text Classification-One txt column' notebook

In [ ]:
############ LR ############

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
# Training
def lr_classifier(X_train, Y_train, C):
    model = LogisticRegression(C=C) # Inverse of regularization strength
    model.fit(X_train, Y_train)
    return model

In [66]:
model = lr_classifier(X_train, Y_train, C=50)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[25  7]
 [ 2 17]]

-------AUC-------

0.8171296296296298

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.78      0.93      0.85        27
           1       0.89      0.71      0.79        24

   micro avg       0.82      0.82      0.82        51
   macro avg       0.84      0.82      0.82        51
weighted avg       0.83      0.82      0.82        51



/home/antrived/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [ ]:
# LR performance improved significantly by using word2vec
    # refer: '9.1 Text Classification-One txt column' notebook

In [83]:
############ XGBoost #############

In [67]:
# conda install -c conda-forge xgboost # some issues
# sudo pip install xgboost
from xgboost import XGBClassifier

In [68]:
# Training
def xgb_classifier(X_train, Y_train, max_depth, learning_rate, n_estimators, objective):
    model = XGBClassifier(max_depth=max_depth, learning_rate=learning_rate, n_estimators=n_estimators, objective=objective)
    model.fit(X_train, Y_train)
    return model

In [81]:
model = xgb_classifier(X_train, Y_train, max_depth=2, learning_rate=0.2, n_estimators=300, 
                       objective='binary:logistic')
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[26 10]
 [ 1 14]]

-------AUC-------

0.7731481481481484

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.72      0.96      0.83        27
           1       0.93      0.58      0.72        24

   micro avg       0.78      0.78      0.78        51
   macro avg       0.83      0.77      0.77        51
weighted avg       0.82      0.78      0.77        51



In [ ]:
# XGBoost performance improved significantly by using word2vec
    # refer: '9.1 Text Classification-One txt column' notebook

In [190]:
############ ANN #############

In [82]:
# importing keras libraries and packages:
import keras
from keras.models import Sequential # to initialize the ANN
from keras.layers import Dense # to create layers of ANN
from keras.layers import Dropout

Using TensorFlow backend.


In [84]:
# Creating Basic ANN

np.random.seed(100) # works. gives close results on repeating but not exactly same.

# Initializing ANN
model = Sequential()

i = 0.20
j = 125

# Adding input layer and 1st hidden layer
model.add(Dense(activation="relu", input_dim=100, units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
# Adding 2nd hidden layer
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=70, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=7, kernel_initializer="uniform"))
# # Adding hidden layer

# Adding output layer
model.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN (means run SGD on ANN)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting ANN to training set
model.fit(X_train, Y_train, batch_size=5, epochs=40)

Instructions for updating:
Use tf.cast instead.
Epoch 1/40
119/119 [==============================] - 1s 8ms/step - loss: 0.6919 - acc: 0.5630
Epoch 2/40
119/119 [==============================] - 0s 717us/step - loss: 0.6842 - acc: 0.6134
Epoch 3/40
119/119 [==============================] - 0s 573us/step - loss: 0.6255 - acc: 0.6134
Epoch 4/40
119/119 [==============================] - 0s 623us/step - loss: 0.5867 - acc: 0.6134
Epoch 5/40
119/119 [==============================] - 0s 848us/step - loss: 0.6868 - acc: 0.6134
Epoch 6/40
119/119 [==============================] - 0s 672us/step - loss: 0.6812 - acc: 0.6134
Epoch 7/40
119/119 [==============================] - 0s 675us/step - loss: 0.6161 - acc: 0.6387
Epoch 8/40
119/119 [==============================] - 0s 668us/step - loss: 0.4909 - acc: 0.7899
Epoch 9/40
119/119 [==============================] - 0s 693us/step - loss: 0.4792 - acc: 0.8235
Epoch 10/40
119/119 [==============================] - 0s 801us/step - loss: 0.42

In [85]:
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[ 0  0]
 [27 24]]

-------AUC-------

0.5

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        27
           1       0.47      1.00      0.64        24

   micro avg       0.47      0.47      0.47        51
   macro avg       0.24      0.50      0.32        51
weighted avg       0.22      0.47      0.30        51



/home/antrived/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [230]:
# FastText gave better results than tf-idf, gensin w2v, glove
    # refer: '9.1 Text Classification-One txt column' notebook
    # FastText best acc is from svm(rbf) and log_reg - 0.8171

In [ ]:
###############################################################
################ Text Classification Scoring
###############################################################

In [ ]:
# You can use 'averaged_word_vectorizer' for new incoming data (check above)
 # the way it is used for current 'tokenized_corpus'

In [ ]:
###############################################################
################ Text Classification Accuracy - GloVe
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - FastText
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - FastText
###############################################################