Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.8
The server is running on this version of Python:
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]

Current Kernel Information:
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
#### Implement Embeddings and evaluate them using text classification
## Key Source - https://towardsdatascience.com/understanding-feature-engineering-part-4-deep-learning-methods-for-text-data-96c44370bbfa
## Algos implemented - Word2Vec, GloVe and FastText

In [ ]:
###### STEPS:

#### Embeddings Generation - Word2Vec
#### Embeddings Generation - Gensim-Word2Vec
#### Text Classification Accuracy - Gensim-Word2Vec

#### Embeddings Generation - GloVe
#### Text Classification Accuracy - GloVe

#### Embeddings Generation - FastText
#### Text Classification Accuracy - FastText

In [ ]:
###############################################################
################ Embeddings Generation - Word2Vec
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - Gensim-Word2Vec
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - Gensim-Word2Vec
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - GloVe
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - GloVe
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - FastText
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - FastText
###############################################################

In [1]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import numpy as np  
import re  # regular expressions like '+', '*'
import nltk  # The Natural Language Toolkit
from sklearn.datasets import load_files  
# nltk.download('popular') 
# will download stopwords, punkt etc # download in default dir else error later on
import pickle  
from nltk.corpus import stopwords
from nltk import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [2]:
## importing data
# Windows 
# hollybolly_inc=pd.read_excel("C:/Users/anurag.trivedi/Dropbox/Job 06 Sep 2018/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly Increased.xlsx",sheet_name='HollyBolly Increased')
# Linux
hollybolly_inc=pd.read_csv("/home/antrived/Dropbox/Job-25-Feb-2019/prep/13. Data/1. Real Data/11. Text Classification Data/1. HollyBolly/HollyBolly_Increased_V2.csv", encoding='ISO-8859-1')
hollybolly = hollybolly_inc
hollybolly.head(10)

Industry                                          Wiki_Text
0  Hollywood  is a neighborhood in the central region of Los...
1  Hollywood  including several of its historic studios. Its...
2  Hollywood  ethnically diverse, densely populated, economi...
3  Hollywood  Hollywood was a small community in 1870 and wa...
4  Hollywood  1910, and soon thereafter a prominent film in...
5  Hollywood  In 1853, one adobe hut stood in Nopalera (No...
6  Hollywood  community flourished. The area was known as th...
7  Hollywood  According to the diary of H. J. Whitley, kno...
8  Hollywood  carrying wood. The man got out of the wagon an...
9  Hollywood  represent England and wood would represent his...

In [3]:
## Labelling
hollybolly.Industry[hollybolly.Industry == "Hollywood"] = 1
hollybolly.Industry[hollybolly.Industry == "Bollywood"] = 0

In [4]:
Y = hollybolly.iloc[:,0].values
type(Y) # numpy array
Y
# sum(hollybolly.Industry)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [5]:
X = hollybolly.iloc[:,1].values.tolist() 
print(type(X)) # X is list
print(X)

<class 'list'>
['is a neighborhood in the central region of Los Angeles, California. The neighborhood is notable for its place as the home of the U.S. film industry, ', 'including several of its historic studios. Its name has come to be aÂ\xa0metonymfor theÂ\xa0motion picture industry of the United States. Hollywood is also a highlyÂ\xa0', 'ethnically diverse, densely populated, economically diverse neighborhood and retail business district.', 'Hollywood was a small community in 1870 and was incorporated as a municipality in 1903.[3][4]Â\xa0It officially merged with the city of Los Angeles inÂ\xa0', '1910, and soon thereafter a prominentÂ\xa0film industryÂ\xa0began to emerge, eventually becoming the most recognizable film industry in the world.[5][6]', 'In 1853, oneÂ\xa0adobeÂ\xa0hut stood in Nopalera (NopalÂ\xa0field), named for the MexicanÂ\xa0Nopal cactusÂ\xa0indigenous to the area. By 1870, an agriculturalÂ\xa0', 'community flourished. The area was known as theÂ\xa0Cahuenga Valley,

In [6]:
## Cleaning - run either Clean1 or Clean2

In [7]:
# Clean1 (run either Clean1 or Clean2)
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # removes unicode characters

    
def remove_stopwords(sentence):
    stop_words = set(stopwords.words("english"))
    return " ".join([word.lower() for word in word_tokenize(sentence)
                    if word.lower() not in stop_words and word.isalpha()])


def clean_stopw_more(text1):
    # removes stopwords, special chars, nums, extra spaces, to lower case etc. (better code)
    # works on list of strings
    documents = []
    for sen in text1:
        documents.append(remove_stopwords(sen))
    return documents


def clean_unicode(text1):
    # removes unicode characters
    # works on list of strings
    documents = []
    for sen in text1:
        sen = str(sen.encode('ascii','ignore'))
        sen = sen[2:]
        sen = sen[:-1]
        sen = " ".join(sen.split())
        documents.append(remove_stopwords(sen))
    return documents


# Lemmatize with POS Tag
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)


def lemmatize(text1):
    # lemmitizes
    # works on list of strings
    documents = []
    lemmatizer = WordNetLemmatizer() 
    for sen in text1:      
        document = ""
        for word in sen.split():
#             word1 = lemmatizer.lemmatize(word) # only removes 's' at the end of nouns as of now
#             word1 = lemmatizer.lemmatize(word, pos ="a") # also converts adjective 'better' to 'good'
            word1 = lemmatizer.lemmatize(word, get_wordnet_pos(word)) # as per word's POS tag
            document = (''.join(document+" "+word1)).strip()
        documents.append(document)
    return documents


X = clean_stopw_more(X)
X = clean_unicode(X)
X = lemmatize(X)
print(X)

['neighborhood central region los angeles california neighborhood notable place home film industry', 'include several historic studio name come metonymfor motion picture industry united state hollywood also highly', 'ethnically diverse densely populate economically diverse neighborhood retail business district', 'hollywood small community incorporate municipality officially merge city los angeles', 'soon thereafter prominent film industry begin emerge eventually become recognizable film industry world', 'one adobe hut stood nopalera nopal field name mexican nopal cactus indigenous area agricultural', 'community flourish area know cahuenga valley pas santa monica mountain immediately north', 'accord diary whitley know father hollywood honeymoon stood top hill look valley along come chinese man wagon', 'carry wood man get wagon bow chinese man ask reply meaning wood whitley epiphany decide name new town hollywood holly would', 'represent england wood would represent scottish heritage whi

In [ ]:
###############################################################
################ Embeddings Generation - Glove
###############################################################

In [8]:
!pip install -U spacy

     |████████████████████████████████| 10.2MB 3.0MB/s eta 0:00:01
     |████████████████████████████████| 184kB 18.4MB/s eta 0:00:01
     |████████████████████████████████| 3.7MB 7.0MB/s eta 0:00:01
     |████████████████████████████████| 122kB 14.1MB/s eta 0:00:01
     |████████████████████████████████| 2.1MB 3.9MB/s eta 0:00:01
  Found existing installation: srsly 0.0.5
    Uninstalling srsly-0.0.5:
      Successfully uninstalled srsly-0.0.5
  Found existing installation: blis 0.2.4
    Uninstalling blis-0.2.4:
      Successfully uninstalled blis-0.2.4
  Found existing installation: preshed 2.0.1
    Uninstalling preshed-2.0.1:
      Successfully uninstalled preshed-2.0.1
  Found existing installation: thinc 7.0.4
    Uninstalling thinc-7.0.4:
      Successfully uninstalled thinc-7.0.4
  Found existing installation: spacy 2.1.4
    Uninstalling spacy-2.1.4:
      Successfully uninstalled spacy-2.1.4
You should consider upgrading via the 'pip install --upgrade pip' command.


In [15]:
!python -m spacy download en_core_web_sm

In [10]:
import spacy
# here we are not training model (maybe Glove can't be retrained/tuned easily - check?)
nlp = spacy.load('en_core_web_sm')
total_vectors = len(nlp.vocab.vectors)
print('Total word vectors:', total_vectors)

Total word vectors: 0


In [18]:
unique_words = list(set([word for sublist in [doc.split() for doc in X] for word in sublist]))

# Glove model creating word embeddings on input words
word_glove_vectors = np.array([nlp(word).vector for word in unique_words])
pd.DataFrame(word_glove_vectors, index=unique_words)

# Note: No training happened here. Only used per-traine model.

0         1         2         3         4         5   \
formally       -0.910511  1.538582 -2.395602 -3.850672 -0.445324  1.834188   
laden          -2.905065  2.892774 -1.956240 -0.537148 -1.602069 -0.780742   
build          -3.649379  0.098734 -1.215481  0.352633  0.388418  0.163593   
five           -1.657039  2.105562 -2.484560  2.653496  0.130330 -1.225245   
within         -0.388274  0.473830 -1.936025 -2.580688 -0.302833  1.255661   
singer         -2.485021  0.548708  0.347878 -0.255191  1.595414  0.400314   
news           -0.793471  0.727232 -1.814361 -1.222901 -0.172258 -1.849825   
canyon         -3.864552 -0.573492 -0.746934 -2.098594 -0.679846  0.390777   
content        -3.451701  1.543935 -0.160281 -2.484357  1.124762 -1.450820   
strip          -0.841797  0.793622 -2.743698 -1.412439 -0.013095  1.445574   
kelly          -1.630101 -0.263947 -1.770626 -4.052517 -2.295602  0.185800   
resurface      -3.263740  1.291363 -1.608329 -2.055328  2.530428  1.604553   
crime          -2.372214 -0.099404 -2.638629 -1.545529  0.632702  1.427692   
affleck        -0.922536  1.317622 -2.673876 -3.989627  0.530728  1.302350   
twin           -3.404208  0.726274 -3.127075 -2.750324 -0.908115 -0.460465   
historic       -0.910734  3.433409 -1.719190 -0.845630 -0.989284 -0.815512   
talk           -1.864951  1.182491 -1.888569 -1.582672 -0.193094  0.171308   
recommendation -1.144161 -0.061375 -1.204862 -3.601424  2.740808  0.036429   
mumbai         -2.034530  0.366260 -2.952319 -3.174567 -0.971400  0.356920   
female         -1.664886  2.964962 -2.368460  0.015397  1.743638 -0.299251   
performance    -2.553285  0.212502 -3.075449 -3.567066  1.163486 -0.295760   
bull           -1.901143 -0.308761  0.317589 -2.700184 -2.355190 -0.024372   
president      -2.361715  0.458351 -1.498456 -2.501853 -0.179338  1.215612   
hotel          -1.842620  1.056177 -0.427946 -0.523763  0.648784 -0.465658   
kamal           0.029244  1.541266 -2.404774 -1.743604  0.093281 -1.590173   
roped          -3.255092  0.830979 -1.175507  0.326620 -0.261418  0.311827   
election       -1.779378  0.538106 -2.476456 -2.860942  1.978808 -0.965511   
assistant      -3.101705  0.283395 -1.890879 -0.359824 -2.574707 -1.150429   
satyam         -1.424302  0.269897 -1.055881 -1.842578  0.790704  0.542304   
nagar          -0.214114  0.697376 -0.312550 -2.758561 -1.009882  0.740322   
...                  ...       ...       ...       ...       ...       ...   
namak          -2.692409  0.499699  0.559289 -1.102424 -3.920208 -0.415576   
court          -2.629366  0.640784 -3.305348 -3.476903 -1.868044  0.079249   
singular       -2.832601 -0.247829 -2.243145 -0.101201 -0.848855 -0.213548   
arrive         -1.473823  1.105154 -1.250948 -0.953961  1.019418  2.240275   
derek          -2.991241  2.136695 -1.963244 -2.526875 -1.940918 -0.708130   
throw          -1.628332 -0.043739 -0.966109 -1.568241  0.154297 -1.250622   
densely        -0.680734 -0.498202 -1.960312 -3.435225 -0.795810 -0.441760   
show           -2.907494 -0.456898 -0.787839 -0.960279  2.329273  3.705794   
heel           -0.534864  2.792390 -1.198722 -1.560840  1.264129 -0.701601   
arora          -1.632899  3.850921 -1.809447 -2.606431 -1.782887  0.371758   
protect        -1.357983 -0.466143 -2.407711 -2.308190  2.092652  1.461059   
discovers       0.737731  0.215182 -0.202748 -4.575660 -0.951493  0.748936   
college        -2.480700  1.297828 -1.428323 -2.116799 -0.037565 -0.488588   
sprint         -1.399243  0.140571 -1.252396 -1.496109 -3.069788 -0.305959   
step           -1.609563  0.405526 -1.310770 -2.817118  1.015076  1.498146   
abu            -0.872835  1.583465 -0.352527 -3.249506 -2.119246  1.601313   
sport          -1.708464 -1.709683 -1.576267 -2.685326 -0.237339 -0.548789   
teri           -2.065859  2.997281 -2.198152 -0.678075 -3.464302 -2.070681   
manner         -1.057606  1.103661 -1.679570 -2.935898  0.912837 -1.231838   
establish      -3.376832  0.253570 -1.099717

In [21]:
doc_glove_vectors = np.array([nlp(str(doc)).vector for doc in X])
pd.DataFrame(doc_glove_vectors)

0         1         2         3         4         5         6   \
0    0.652554  0.602701 -0.278118 -2.686510 -0.545089 -0.465982 -1.756253   
1   -0.464325  0.498343 -1.533419 -2.012044  0.604191  0.293685 -0.861688   
2   -1.194345  0.785367 -1.308923 -1.212723  0.905295  0.589512  0.365411   
3    0.479789  0.672837 -0.164583 -2.205916 -1.243144 -0.232613 -1.374045   
4   -0.618562  0.845398 -2.139261 -2.173553  0.755895  0.473620  0.869778   
5   -0.828670  0.901748  0.268573 -2.360908 -0.981824 -0.385279 -2.265581   
6    0.159492  1.077553  0.675187 -2.185223 -1.409121 -0.164573 -1.472809   
7   -0.199228  0.877325 -0.400167 -2.255611 -1.006161 -0.285840 -1.439667   
8   -0.603883  0.147538 -0.995781 -2.247153 -0.219783  0.054724 -2.052284   
9    0.106585  0.213982 -1.356720 -1.603543 -0.297565  0.628933 -1.099718   
10  -0.881306  0.801929 -1.059225 -2.378382  0.022562 -0.026226 -1.814331   
11   0.364236  0.386561 -0.081595 -2.662519 -1.547394  0.000075 -2.637946   
12   0.180717  0.727216 -0.481257 -1.948374 -1.507532 -1.282955 -2.531769   
13  -0.513931  0.193037 -0.912085 -2.151218 -0.120436  0.003028 -2.375573   
14  -1.277760  0.612958  0.096247 -1.535640  0.422862  0.458475 -1.594947   
15   0.251363  0.047603  0.642819 -2.361349 -1.001456  0.420428 -2.150589   
16  -0.946818  0.175712 -0.008255 -0.775569  0.312344  0.337263 -0.453910   
17   0.030804  0.501217  0.508240 -2.699124 -1.571276 -0.227006 -1.890911   
18  -0.916125  0.050819 -0.282843 -2.254344 -0.148239  0.252546 -1.957743   
19  -1.268596  0.598575 -0.507731 -1.083940 -0.011795  1.163729 -0.724212   
20  -1.179148 -0.093394 -0.772007 -1.748856  0.338616  0.196873 -0.958113   
21  -1.033182  0.079480 -1.137645 -1.917625 -0.035176 -0.243723 -0.522386   
22  -1.528199  0.536883  0.225836 -2.734136  0.191700 -0.599626 -1.602614   
23  -0.873210 -0.128931 -0.616256 -2.013093 -0.290354 -0.475469 -0.846486   
24  -0.809623  0.203179 -1.546709 -2.504151 -0.151966 -0.037799 -0.660912   
25  -0.507019  0.314583 -1.275164 -2.525727 -0.114421  0.358860 -1.683446   
26   0.376182  1.174116 -1.342119 -2.480564 -0.659430 -0.688944 -1.706216   
27  -0.342549  0.488000 -1.848574 -2.663534  1.050997  0.386110 -0.785337   
28  -0.278709  0.130438 -1.346562 -1.504904 -0.527592  0.545707 -1.416911   
29  -0.182163  0.916233 -0.743074 -2.636889 -1.110025 -0.370852 -1.628264   
..        ...       ...       ...       ...       ...       ...       ...   
140 -0.580520  0.939590 -1.634783 -2.199021  0.840216  0.477185 -1.070597   
141 -0.351357  0.505941 -0.963822 -2.324816 -0.089629  0.217282 -1.369136   
142 -1.781425 -0.044283 -1.403151 -1.697764  0.358689  0.281663 -0.282341   
143 -1.186648  1.728315 -0.282978 -2.393847 -0.675958  0.633513 -1.911934   
144 -1.412836  0.225480 -0.700586 -2.466037 -0.558162 -0.630540 -1.185128   
145 -1.033870  0.294994 -1.877332 -2.439609 -0.499180 -0.118019 -1.456121   
146 -1.032955  0.721998 -1.307975 -2.052846  0.212292 -0.098578 -0.864241   
147 -0.865224  0.435891 -0.313741 -1.744528  0.077873  0.384639 -0.848842   
148 -0.762544  0.137661 -1.593287 -1.242499  0.210756  0.699185  0.261883   
149 -0.968115  0.514879 -0.777347 -2.361910  0.689777 -0.495382 -0.900949   
150 -1.897616  0.015047 -2.805346 -0.833640  2.182535  2.208750 -0.622876   
151 -1.280864  0.223785  0.212580 -2.094110 -0.841030  0.371865 -1.783306   
152 -0.528581  0.347063 -1.833182 -1.601043 -0.007472  0.797541 -0.968200   
153 -0.110665  0.671350 -0.069225 -2.851644 -1.408715 -0.248259 -2.225753   
154 -0.651267 -0.133418 -1.066602 -1.517813 -0.006840  0.659363 -0.939757   
155 -0.558976 -0.162558 -1.568908 -1.984336  0.633329  0.333527 -1.938599   
156  0.284963  1.596577 -1.221784 -1.409691 -0.664662 -0.617987 -0.178125   
157  0.181935  0.623631 -1.784800 -2.194737  0.698139  0.300839  0.295023   
158 -0.314282 -0.121420 -1.724313 -1.613359 -0.270786  0.520130 -1.445833   
159 -0.901150  0.531202 -0.744812 -1.005964 -0.653065  0.719384 -1.645461   
160 -1.

In [24]:
X = doc_glove_vectors

In [ ]:
###############################################################
################ Text Classification Accuracy - Glove-Word_Vectors
###############################################################

In [208]:
## Sampling

In [25]:
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=12)
Y_train = Y_train.astype(int)
Y_test = Y_test.astype(int)
# print(len(X_train)) # 119
# print(len(X_test)) # 51

In [26]:
X_train = np.asmatrix(X_train)
print(X_train)
X_test = np.asmatrix(X_test)
print(X_test)

[[-0.11066513  0.67135024 -0.06922533 ... -2.3671007   1.1260325
  -0.6929709 ]
 [-0.505055    0.6018971  -0.17907833 ... -2.6080956   0.29579028
  -0.1353795 ]
 [-0.35318774 -0.07735105 -0.94227284 ... -2.1859927  -0.610023
  -0.44696772]
 ...
 [-1.2858856   1.8660694  -2.021432   ... -2.4467478   1.3835381
  -1.0250468 ]
 [-0.5589758  -0.162558   -1.5689081  ... -2.055398   -0.51837885
  -1.2475017 ]
 [ 0.86424804  0.9086279  -1.025845   ... -1.5044373   1.242414
  -0.46426594]]
[[-1.3138969   0.20309338 -1.0103899  ... -2.4979334  -0.6231714
  -1.2581191 ]
 [-0.87321013 -0.12893112 -0.6162563  ... -1.9765747   0.06321261
  -0.26395127]
 [-1.1866479   1.7283145  -0.28297818 ... -1.3504851   0.85596496
  -0.15537767]
 ...
 [ 0.5109745   1.540503    1.0681665  ... -2.122074    0.89030033
  -0.21039772]
 [-0.80962336  0.20317915 -1.5467093  ... -2.237671   -0.05340075
  -0.10437691]
 [-1.2685964   0.5985745  -0.50773084 ... -1.6834233  -0.05009285
  -0.5840333 ]]


In [27]:
# Import classification related packages
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import classification_report

In [14]:
############# Random Forest ###############

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
# Training
def rf_classifier(X_train, Y_train, n_estimators, max_depth, max_features, random_state):
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features, random_state=random_state)   
    Y_train = np.asarray(Y_train, dtype="|S6")
    model.fit(X_train, Y_train)
    return model

def rf_predictions(model, X_test, Y_test):
    y_pred = model.predict_proba(X_test) # default 'predict' gives 'categorical' predictions for RF
    # classifier.classes_ # to check order of classes in 'predict_proba' (most prob. it's 0,1...)
    y_pred = y_pred[:,1] # accessing 2nd column or '1' class probabilities
    # converting prob to 1/0 and array type to int
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred
    
def create_reports(y_pred, Y_test):
    # creating CF matrix
    Y_test = Y_test.astype(int)
    y_pred = y_pred.astype(int)
    cm1 = confusion_matrix(y_pred, Y_test)
    print("\n--Confusion Matrix--\n")
    print(cm1)
    # calculating auc
    fp_rate, tp_rate, thresholds = roc_curve(Y_test, y_pred)
    print("\n-------AUC-------\n")
    print(auc(fp_rate, tp_rate))
    print("\n----------------Classification_Report------------------\n")
    print(classification_report(Y_test, y_pred))

In [44]:
model = rf_classifier(X_train, Y_train, n_estimators=500, max_depth=8, max_features=3, random_state=0)
y_pred = rf_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[24 20]
 [ 3  4]]

-------AUC-------

0.5277777777777778

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.55      0.89      0.68        27
           1       0.57      0.17      0.26        24

   micro avg       0.55      0.55      0.55        51
   macro avg       0.56      0.53      0.47        51
weighted avg       0.56      0.55      0.48        51



In [18]:
# Insight: Performance improved drastically over RF using regular text classification
    # refer: '9.1 Text Classification-One txt column' notebook

In [19]:
############# Linear/Non-Linear SVM ###############

In [45]:
from sklearn.svm import SVC 

In [46]:
# Training
def svm_classifier(X_train, Y_train, kernel, C, gamma):
    model = SVC(kernel=kernel, C=C, gamma=gamma) # kernel = rbf/linear 
    model.fit(X_train, Y_train) 
    return model

def common_predictions(model, X_test, Y_test):
    y_pred = model.predict(X_test)
    y_pred = y_pred.astype(int)
    y_pred[y_pred > 0.5] = 1
    y_pred[y_pred <= 0.5] = 0
    return y_pred

In [57]:
model = svm_classifier(X_train, Y_train, kernel='rbf', C=20, gamma=0.01)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[22 16]
 [ 5  8]]

-------AUC-------

0.5740740740740741

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.58      0.81      0.68        27
           1       0.62      0.33      0.43        24

   micro avg       0.59      0.59      0.59        51
   macro avg       0.60      0.57      0.55        51
weighted avg       0.60      0.59      0.56        51



In [319]:
# Insight: performance of SVM dipped by using word2vec
    # because number of vars have reduced from 1500 to 100 and N performs well with more vars
    # refer: '9.1 Text Classification-One txt column' notebook

In [320]:
############# Naive Bayes ###############

In [58]:
from sklearn.naive_bayes import GaussianNB

In [59]:
# Training
def nb_classifier(X_train, Y_train):
    model = GaussianNB()
    temp = X_train.copy()
    model.fit(temp, Y_train)
    return model

In [60]:
model = nb_classifier(X_train, Y_train)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[19 13]
 [ 8 11]]

-------AUC-------

0.5810185185185185

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.59      0.70      0.64        27
           1       0.58      0.46      0.51        24

   micro avg       0.59      0.59      0.59        51
   macro avg       0.59      0.58      0.58        51
weighted avg       0.59      0.59      0.58        51



In [82]:
# Insight: performance of NB dipped by using word2vec
    # because number of vars have reduced from 1500 to 100 and N performs well with more vars
    # refer: '9.1 Text Classification-One txt column' notebook

In [ ]:
############ LR ############

In [61]:
from sklearn.linear_model import LogisticRegression

In [62]:
# Training
def lr_classifier(X_train, Y_train, C):
    model = LogisticRegression(C=C) # Inverse of regularization strength
    model.fit(X_train, Y_train)
    return model

In [65]:
model = lr_classifier(X_train, Y_train, C=50)
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[20 14]
 [ 7 10]]

-------AUC-------

0.5787037037037037

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.59      0.74      0.66        27
           1       0.59      0.42      0.49        24

   micro avg       0.59      0.59      0.59        51
   macro avg       0.59      0.58      0.57        51
weighted avg       0.59      0.59      0.58        51



/home/antrived/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [ ]:
# LR performance improved significantly by using word2vec
    # refer: '9.1 Text Classification-One txt column' notebook

In [83]:
############ XGBoost #############

In [66]:
# conda install -c conda-forge xgboost # some issues
# sudo pip install xgboost
from xgboost import XGBClassifier

In [67]:
# Training
def xgb_classifier(X_train, Y_train, max_depth, learning_rate, n_estimators, objective):
    model = XGBClassifier(max_depth=max_depth, learning_rate=learning_rate, n_estimators=n_estimators, objective=objective)
    model.fit(X_train, Y_train)
    return model

In [73]:
model = xgb_classifier(X_train, Y_train, max_depth=5, learning_rate=0.2, n_estimators=500, objective='binary:logistic')
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[21 15]
 [ 6  9]]

-------AUC-------

0.5763888888888888

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.58      0.78      0.67        27
           1       0.60      0.38      0.46        24

   micro avg       0.59      0.59      0.59        51
   macro avg       0.59      0.58      0.56        51
weighted avg       0.59      0.59      0.57        51



In [ ]:
# XGBoost performance improved significantly by using word2vec
    # refer: '9.1 Text Classification-One txt column' notebook

In [190]:
############ ANN #############

In [74]:
# importing keras libraries and packages:
import keras
from keras.models import Sequential # to initialize the ANN
from keras.layers import Dense # to create layers of ANN
from keras.layers import Dropout

Using TensorFlow backend.


In [76]:
# Creating Basic ANN

np.random.seed(100) # works. gives close results on repeating but not exactly same.

# Initializing ANN
model = Sequential()

i = 0.20
j = 125

# Adding input layer and 1st hidden layer
model.add(Dense(activation="relu", input_dim=96, units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
# Adding 2nd hidden layer
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dropout(rate=i))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# model.add(Dense(activation="relu", units=j, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=70, kernel_initializer="uniform"))
# # Adding hidden layer
# classifier.add(Dense(activation="relu", units=7, kernel_initializer="uniform"))
# # Adding hidden layer

# Adding output layer
model.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN (means run SGD on ANN)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting ANN to training set
model.fit(X_train, Y_train, batch_size=5, epochs=40)

Instructions for updating:
Use tf.cast instead.
Epoch 1/40
119/119 [==============================] - 1s 9ms/step - loss: 0.6923 - acc: 0.5630
Epoch 2/40
119/119 [==============================] - 0s 491us/step - loss: 0.6878 - acc: 0.6134
Epoch 3/40
119/119 [==============================] - 0s 469us/step - loss: 0.6640 - acc: 0.6134
Epoch 4/40
119/119 [==============================] - 0s 472us/step - loss: 0.6732 - acc: 0.6134
Epoch 5/40
119/119 [==============================] - 0s 447us/step - loss: 0.6585 - acc: 0.6134
Epoch 6/40
119/119 [==============================] - 0s 585us/step - loss: 0.6389 - acc: 0.6134
Epoch 7/40
119/119 [==============================] - 0s 563us/step - loss: 0.6037 - acc: 0.6134
Epoch 8/40
119/119 [==============================] - 0s 641us/step - loss: 0.5720 - acc: 0.6134
Epoch 9/40
119/119 [==============================] - 0s 731us/step - loss: 0.6179 - acc: 0.6218
Epoch 10/40
119/119 [==============================] - 0s 649us/step - loss: 0.55

In [77]:
y_pred = common_predictions(model, X_test, Y_test)
create_reports(y_pred, Y_test)


--Confusion Matrix--

[[27 24]
 [ 0  0]]

-------AUC-------

0.5

----------------Classification_Report------------------

              precision    recall  f1-score   support

           0       0.53      1.00      0.69        27
           1       0.00      0.00      0.00        24

   micro avg       0.53      0.53      0.53        51
   macro avg       0.26      0.50      0.35        51
weighted avg       0.28      0.53      0.37        51



/home/antrived/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [230]:
# Glove pre-trained model is used without tuning, probably that's why
    # results are not up to the mark compared to Gensim and tf-idf based TC
    # refer: '9.1 Text Classification-One txt column' notebook
    # Spacy Glove best acc is from Naive Bayes - 0.58

In [ ]:
# Re-training Glove: seems no ready-made way available:
# https://datascience.stackexchange.com/questions/33792/how-to-retrain-glove-vectors-on-top-of-my-own-data

In [ ]:
###############################################################
################ Text Classification Accuracy - GloVe
###############################################################

In [ ]:
###############################################################
################ Embeddings Generation - FastText
###############################################################

In [ ]:
###############################################################
################ Text Classification Accuracy - FastText
###############################################################